interface Env {
  DB: D1Database;
  GITHUB_TOKEN: string;
}

interface SuggestionRow {
  id: string;
  suggestion_type: string;
  title: string;
  proposed_change: string | null;
  files_affected: string | null;
  deployment_steps: string | null;
}

const REPO_OWNER = "LiamFuller07";
const REPO_NAME = "moltclip";

export async function deploySuggestion(
  env: Env,
  suggestionId: string,
): Promise<{ success: boolean; pr_url?: string; error?: string }> {
  if (!env.GITHUB_TOKEN) {
    return { success: false, error: "GITHUB_TOKEN not configured" };
  }

  const suggestion = await env.DB.prepare(
    "SELECT * FROM harness_suggestions WHERE id = ? AND status = 'approved'",
  ).bind(suggestionId).first<SuggestionRow>();

  if (!suggestion) {
    return { success: false, error: "Suggestion not found or not approved" };
  }

  const deployId = `deploy_${Date.now()}`;
  const branchName = `harness/${suggestion.suggestion_type}/${Date.now()}`;

  try {
    // Get default branch SHA
    const repoRes = await ghFetch(env, `/repos/${REPO_OWNER}/${REPO_NAME}`);
    const repoData = (await repoRes.json()) as { default_branch: string };
    const defaultBranch = repoData.default_branch;

    const refRes = await ghFetch(
      env,
      `/repos/${REPO_OWNER}/${REPO_NAME}/git/ref/heads/${defaultBranch}`,
    );
    const refData = (await refRes.json()) as { object: { sha: string } };
    const baseSha = refData.object.sha;

    // Create branch
    await ghFetch(env, `/repos/${REPO_OWNER}/${REPO_NAME}/git/refs`, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
    });

    // Create PR (without actual file changes for now — the PR body describes what to do)
    const prBody = [
      `## Harness Suggestion: ${suggestion.title}`,
      "",
      `**Type**: ${suggestion.suggestion_type}`,
      `**ID**: ${suggestion.id}`,
      "",
      "### Proposed Change",
      suggestion.proposed_change ?? "No specific change proposed",
      "",
      "### Files Affected",
      suggestion.files_affected ?? "[]",
      "",
      "### Deployment Steps",
      suggestion.deployment_steps ?? "[]",
      "",
      "---",
      "*Auto-generated by MoltClip Harness Worker*",
    ].join("\n");

    const prRes = await ghFetch(
      env,
      `/repos/${REPO_OWNER}/${REPO_NAME}/pulls`,
      {
        method: "POST",
        body: JSON.stringify({
          title: `[Harness] ${suggestion.title}`,
          body: prBody,
          head: branchName,
          base: defaultBranch,
        }),
      },
    );

    const prData = (await prRes.json()) as { html_url?: string; number?: number };

    // Record deployment
    await env.DB.prepare(
      "INSERT INTO deployment_history (id, suggestion_id, deployment_timestamp, deployment_type, git_pr_url, test_passed, deployed_by) VALUES (?, ?, ?, ?, ?, ?, ?)",
    )
      .bind(
        deployId,
        suggestionId,
        new Date().toISOString(),
        suggestion.suggestion_type,
        prData.html_url ?? null,
        0,
        "harness-worker",
      )
      .run();

    // Update suggestion status
    await env.DB.prepare(
      "UPDATE harness_suggestions SET status = 'deployed', deployed_at = ?, deployment_result = ? WHERE id = ?",
    )
      .bind(
        new Date().toISOString(),
        JSON.stringify({ pr_url: prData.html_url, pr_number: prData.number }),
        suggestionId,
      )
      .run();

    return { success: true, pr_url: prData.html_url };
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);

    await env.DB.prepare(
      "INSERT INTO deployment_history (id, suggestion_id, deployment_timestamp, deployment_type, error_log, deployed_by) VALUES (?, ?, ?, ?, ?, ?)",
    )
      .bind(
        deployId,
        suggestionId,
        new Date().toISOString(),
        suggestion.suggestion_type,
        error,
        "harness-worker",
      )
      .run();

    await env.DB.prepare(
      "UPDATE harness_suggestions SET status = 'failed', deployment_result = ? WHERE id = ?",
    )
      .bind(JSON.stringify({ error }), suggestionId)
      .run();

    return { success: false, error };
  }
}

function ghFetch(
  env: Env,
  path: string,
  init?: RequestInit,
): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init?.headers ?? {}),
    },
  });
}
